# Generated by Django 5.0.1 on 2024-01-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatmessage_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
